# Generated by Django 5.2 on 2026-02-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='documents_submitted',
            field=models.TextField(blank=True, help_text='Comma-separated list of documents'),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_duration',
            field=models.IntegerField(default=0, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='loan',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed_full', 'Employed (Full-time)'), ('employed_part', 'Employed (Part-time)'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student'), ('disability', 'Disability Benefits')], max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('auto', 'Auto Loan'), ('home', 'Home Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('emergency', 'Emergency Loan')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='net_disbursal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Active', 'Active'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
